# MCU
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# enable
LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
NKRO_ENABLE = yes
# OLED_ ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
RGBLIGHT_ENABLE = no
ENCODER_MAP_ENABLE = yes
#disable
BOOTMAGIC_ENABLE =no
RGBLIGHT_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SLEEP_LED_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE =no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
