#pragma once

#define VIAL_KEYBOARD_UID {0x2E, 0xA1, 0x1C, 0xA5, 0xCF, 0x07, 0xCC, 0x8C}
// #define VIAL_KEY_OVERRIDE_ENTRIES 5
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4